server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
#      uri:  mongodb://root:123@localhost:27017
      uri:  mongodb://localhost
      database: xc_cms